version: '3'

services:
  kvstore:
    restart: always
    image: redis:latest
    ports:
      - "127.0.0.1:6379:6379"

  database:
    restart: always
    image: postgres:latest
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_PASSWORD=password

  smtp:
    restart: always
    image: catatnight/postfix:latest
    ports:
      - "127.0.0.1:25:25"
      - "127.0.0.1:587:587"
    environment:
      - maildomain=mail.example.com
      - smtp_user=user:pwd

  s3:
    ports:
      - "127.0.0.1:9000:9000"
    image: minio/minio:latest
    environment:
      - MINIO_REGION=eu-central-1
      - MINIO_SECRET_KEY=foobar
      - MINIO_ACCESS_KEY=foobar

  proxy:
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
