version: '3'

services:
  kvstore:
    restart: always
    image: redis:latest
    ports:
      - "127.0.0.1:6379:6379"

  database:
    restart: always
    image: postgres:latest
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - dbdata:/var/lib/postgresql/data

  smtp:
    restart: always
    image: catatnight/postfix:latest
    ports:
      - "127.0.0.1:25:25"
      - "127.0.0.1:587:587"
    environment:
      - maildomain=mail.example.com
      - smtp_user=user:pwd

  files:
    ports:
      - "127.0.0.1:9000:9000"
    image: minio/minio:latest
    environment:
      - MINIO_SECRET_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    volumes:
      - filesdata:/data
    command: server /data

  proxy:
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"

  static:
    restart: always
    image: nginx:latest
    ports:
      - "127.0.0.1:3000:80"
    volumes:
      - ./static:/usr/share/nginx/html

volumes:
  dbdata:
    external: false
  filesdata:
    external: false
