version: '3'

services:
  kvstore:
    restart: always
    image: redis:latest

  database:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - dbdata:/var/lib/postgresql/data

  smtp:
    restart: always
    image: catatnight/postfix:latest
    environment:
      - maildomain=mail.myps.net
      - smtp_user=user:pwd

  files:
    restart: always
    image: minio/minio:latest
    environment:
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - MINIO_DOMAIN=minio.myps.net
      - VIRTUAL_HOST=minio.myps.net
    volumes:
      - filesdata:/data
    command: server /data

  nginx-proxy:
    restart: always
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  static:
    restart: always
    image: nginx:latest
    volumes:
      - ./static:/usr/share/nginx/html
    environment:
      - VIRTUAL_HOST=static.myps.net

  app:
    build: ./app
    restart: always
    image: thedefaulstack/app
    environment:
      - VIRTUAL_HOST=app.myps.net

volumes:
  dbdata:
    external: false
  filesdata:
    external: false
